export const BUTTON_CLICKED_SUCESS = 'BUTTON_CLICKED_SUCESS'
export const BUTTON_CLICKED_FAILURE = 'BUTTON_CLICKED_FAILURE'
export const BUTTON_CLICKED_REQUEST = 'BUTTON_CLICKED_REQUEST'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE'